### PR TITLE
Updated package, added babel-preset-es2015, and added  syntax

### PR DESCRIPTION
**Pull request by zacjones93**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Looks like the other PR is unnecessary with this one. I'm assuming everything still works? :-)

**Comment by zacjones93** [comment]
Yeah, everything works! :)

**Comment by kentcdodds** [comment]
Just saw all your PRs come in. I'm not really doing anything with this repo... Do you want me to just give you commit access? That'd probably be easiest.

**Comment by kentcdodds** [comment]
Whoops... Got confused for a second. This is my egghead lesson repo... Heh, I hope you don't mind me retracting my offer. Because I'm responsible for people who learn from my lessons, I'd like to maintain control. :-)

But thanks for your PRs. Do you suppose could you put all of those commits into a single PR? It appears line they all kinds of depend on each other anyway. Let me know if you need help with that. Thanks!

**Comment by zacjones93** [comment]
Yeah, I wasn't sure I wanted the power of committing directly (Joel said don't do it) haha and I'm not quite sure how I would put all these commits into a single PR. Still kinda new to git.

**Comment by zacjones93** [comment]
Joel said he was fine with Ian reviewing them if that was something you wanted to do.

**Comment by kentcdodds** [comment]
Be sure to tell Joel that I was confused about which repository was and that I do still care about this project. Sorry!

> Joel said he was fine with Ian reviewing them if that was something you wanted to do.

I'm not sure what you mean by this.

**Pull request merged**
